---
jobs:
- name: build-unit-test
  public: true
  serial: true
  plan:
  - aggregate:
    - get: source-code
      trigger: true
    - get: my-code
    - get: rc-version
      trigger: false
      resource: app-version
      params:
        bump: minor
        pre: rc
  - task: build-unit-test
    config:
      platform: linux
      image: docker:///pierrevincent/gradle-java8
      inputs:
        - name: source-code
        - name: my-code
        - name: rc-version
      run:
        path: my-code/build-unit-test.sh
        args: [source-code, hello-world-app, rc-version/number]
  - put: rc-version
    resource: app-version
    params: 
      file: rc-version/number
  - put: artifact-repo
    params:
      from: build-unit-test/hello-world-app(.)+\.war

- name: dev-deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: my-code
    - get: artifact-repo
      params:
       filename: hello-world-app(.)+\.war
       version: rc-version/number
      passed: [build-unit-test]
      trigger: true
    - get: deployment-manifest-store
      params:
       filename: hello-world-app-(?=[A-Z][a-z])+-([0-9]+\.[0-9]+\.[0-9]+).yml
       #filename: hello-world-app-dev-([0-9]+\.[0-9]+\.[0-9]+).yml
  - task: setup-cf-push
    config:
      platform: linux
      inputs: 
        - name: artifact-repo
        - name: deployment-manifest-store
        - name: my-code
      run:
        path: my-code/dev-deploy.sh
        args: [artifact-repo, deployment-manifest-store]
  - aggregate:
    - put: dev-cf
      params:
        manifest: setup-cf-push/manifest.yml
        path: setup-cf-push/deployable-artifact.war

- name: func-test
  public: true
  serial: true
  plan:
  - aggregate:
    - get: my-code      
    - get: deployment-manifest-store
      params:
        filename: hello-world-app-(?=[A-Z][a-z])+-([0-9]+\.[0-9]+\.[0-9]+).yml
    - get: source-code
      #passed: [dev-deploy]
  - task: func-test
    config:
      platform: linux
      image: docker:///owaism/ubuntu-java8-gradle-ruby
      inputs:
      - name: source-code
      - name: my-code
      run:
        path: my-code/func-test.sh
        args: [source-code]
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/owaism/java-helloworld-concourse-sample.git
- name: my-code
  type: git
  source:
    uri: https://github.com/owaism/hello-world-concourse-poc.git
- name: dev-cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false
- name: artifact-repo
  type: s3
  source:
    access_key_id: {{aws_access_key}}
    secret_access_key: {{aws_secret_key}}
    bucket: {{s3-rc-artifact-bucket}}
    regexp: hello-world-poc-([0-9]+\.[0-9]+\.[0-9]+)\.jar
    endpoint: s3-us-west-2.amazonaws.com
- name: deployment-manifest-store
  type: s3
  source:
    access_key_id: {{aws_access_key}}
    secret_access_key: {{aws_secret_key}}
    bucket: {{s3-deployment-manifest-bucket}}
    regexp: hello-world-app-dev-([0-9]+\.[0-9]+\.[0-9]+).yml
    endpoint: s3-us-west-2.amazonaws.com
- name: app-version
  type: semver
  source:
    bucket: {{s3-artifact-version-bucket}}
    key: hello-word-poc
    access_key_id: {{aws_access_key}}
    secret_access_key: {{aws_secret_key}}
    endpoint: s3-us-west-2.amazonaws.com

